name: build
on:
  workflow_dispatch: null
  release:
    types:
      - published
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
          - os: macos-latest
          - os: windows-2019
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --ignore-scripts
      - run: npm run prebuild
      - uses: actions/upload-artifact@v3
        with:
          name: prebuilds
          path: prebuilds
  publish:
    name: Publishing to NPM
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - uses: actions/download-artifact@v3
        with:
          name: prebuilds
          path: prebuilds
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
